version: '3'
services:
  # Override base compose file like this:
  # graph-node:
  #   environment:
  #     - ethereum='local:0.0.0.0'

  # TODO: Start the testchain with deployed contracts
  testchain:
    image: <TODO>
    ports:
      - 8545:8545
