version: '3'
services:
  graph-node:
    # To define in .env file
    environment:
      postgres_pass: ${POSTGRES_PASSWORD}
      # i.g: : mainnet:http://mainnet.infura.io/API_KEY/'
      ethereum: '${NETWORK}:${ETHEREUM_RPC}'
  postgres:
    # To define in .env file
    environment:
      - POSTGRES_PASSWORD
  graph-deployer:
    build: ../
    depends_on:
      - graph-node
      - postgres
    environment:
      - GRAPH_ADMIN_RPC_URL=http://graph-node:8020/
      - IPFS_URL=http://ipfs:5001
      - SUBGRAPH_NAME=reflexer-labs/rai
      - NETWORK
    command: './docker/wait-for-it.sh\ graph-node:8000\ --timeout=40\ &&\ npm\ run\ deploy-local'
