on:
  push:
    branches:
      - master

name: Deploy to VM

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
#     - name: save private key to file
#       run: |
#         echo $SSH_PRIVATE_KEY > key.pem
#         sudo chmod 600 key.pem
#       env:
#         SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
#     - name: Install SSH key
#       uses: shimataro/ssh-key-action@v2
#       with:
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         name: id_rsa
#         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
       ETHEREUM_RPC: ${{secrets.ETHEREUM_RPC}}
       POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
       NETWORK: ${{secrets.NETWORK}}
      with:
        host: ${{ secrets.VM_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        envs: ETHEREUM_RPC,POSTGRES_PASSWORD,NETWORK
        script: |
          if docker container ls | grep -q graph-node
          then 
          echo "Redeploy subgraph only..."
          cd geb-subgraph/docker
          docker-compose stop graph-node
          git pull
          sudo chmod -R 777 data/
          docker-compose start graph-node
          docker-compose up --build graph-deployer
          else
          echo "Redeploy all..."
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          sudo rm -rf geb-subgraph
          git clone https://github.com/reflexer-labs/geb-subgraph
          cd geb-subgraph/docker
          echo ETHEREUM_RPC=$ETHEREUM_RPC >> .env
          echo NETWORK=$NETWORK >> .env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
          docker-compose up --build -d
          fi
#     - name: deploy over ssh
#       env:
#         VM_IP: ${{ secrets.VM_IP }}
#         ETHEREUM_RPC: ${{secrets.ETHEREUM_RPC}}
#         POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
#         NETWORK: ${{secrets.NETWORK}}
#       run: |
#         ssh ubuntu@$VM_IP ls
#           export ETHEREUM_RPC=https://parity0.kovan.makerfoundation.com:8545
#           export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
#           export NETWORK=$NETWORK
#           bash -c '
#               echo "Cleaup..."
#               docker stop $(docker ps -aq)
#               docker rm $(docker ps -aq)
#               rm -rf geb-subgraph
#               echo "Clone repo..."
#               git clone https://github.com/reflexer-labs/geb-subgraph
#               cd geb-subgraph/docker
#               if docker-compose ps --services | grep graph-node
#               then 
#               echo "Redeploy subgraph only..."
#               sudo chmod -R +rxw data/
#               docker-compose up --build graph-deployer
#               else
#               echo "Redeploy all..."
#               sudo rm -rf data
#               docker-compose up --build -d
#               fi
#               '
   
